Created the PR-template
krshkodes/username-checker pull request #15
Opened 2022-04-28 18:50 UTC by jaynarayan-vaishnav

created and added the necessary info to PR template.

2022-04-28 19:19 UTC, jaynarayan-vaishnav commented
I have completed both the tasks as you have said pls check if its done correctly @krshkodes

2022-04-30 03:28 UTC, krshkodes requested changes
It looks good, but in the issue templates there is no end line, please add an empty line at the end, and this PR is ready to go!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-04-30 06:47 UTC, jaynarayan-vaishnav commented
Okay will complete it today✌🏻

2022-04-30 09:58 UTC, jaynarayan-vaishnav commented
hey, @krshkodes I have added the end lines on the ISSUE_TEMPLATE files. but there were too many commits so I force pushed it into my forked repo is it okay?

2022-05-01 06:08 UTC, krshkodes requested changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-05-01 06:08 UTC, krshkodes commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +
```suggestion

```

2022-05-01 06:08 UTC, krshkodes commented on .github/ISSUE_TEMPLATE/config.yml
> +
```suggestion

```

2022-05-01 06:08 UTC, krshkodes commented on .github/ISSUE_TEMPLATE/documentation.yml
> +
```suggestion

```

2022-05-01 06:08 UTC, krshkodes commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +
```suggestion

```

2022-05-01 06:08 UTC, krshkodes commented on .github/ISSUE_TEMPLATE/other.yml
> +
```suggestion

```

2022-05-01 10:48 UTC, jaynarayan-vaishnav commented
i need to remove the space in the end line right? or is it something else pls explain

2022-05-01 15:55 UTC, krshkodes approved these changes
Yeah, it was the spaces! Thanks for the contribution, It looks good to me, thus merging!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-01 15:56 UTC, merged

2022-05-01 16:55 UTC, jaynarayan-vaishnav commented
thanks @krshkodes  if there's anything i can help with i would love to do more 😄