feat:contributing guide is added
krshkodes/username-checker pull request #18
Opened 2022-07-17 13:45 UTC by Kshitiz-Mhto

## Related Issue

Closes: #5

### Describe the changes you've made

## How has this been tested?

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] I have followed the code style of the project
- [x] I have tested my code, and it works without errors

## Additional Information

 
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/CeruleanCodersComm/.github/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/krshname/username-checker/pull/18"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-07-21 13:05 UTC, KendallDoesCoding commented
@frazie wanted to work on this..

2022-07-22 09:07 UTC, KendallDoesCoding commented
Hey Kshitz,

No worries. I do the same thing half the time, but just letting you know
that if its assigned, you should ask before you work on the issue, because
incase the other person has started work it wastes everyones time.

Frazie doesnt seem to have started work on this.

Nono, no worries. The code looks good, don't close the PR :))

Thanks,


On Fri, 22 Jul 2022, 9:43 am Kshitiz Mhto, ***@***.***> wrote:

> heartly sry for that but i think @frazie <https://github.com/frazie> is
> not working on this. it has been almost a month so i gave a try.
> @KendallDoesCoding <https://github.com/KendallDoesCoding> , do you want
> me to close it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/krshname/username-checker/pull/18#issuecomment-1191542624>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUGJUTM4RTQ2M7GBIOMFGPDVVINVBANCNFSM53ZZBJCA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-22 10:26 UTC, KendallDoesCoding commented on .github/CONTRIBUTING_GUIDE.md
> +* **Include screenshots or animated GIFs** which show you following the described steps and clearly demonstrate the problem. If you use the keyboard while following the steps, use [this tool](https:/
You can delete the following lines as they are not required

```
If you use the keyboard while following the steps, use [this tool](https://www.cockos.com/licecap/) to record GIFs on macOS and Windows, and [this tool](https://github.com/colinkeenan/silentcast) or [this tool](https://github.com/GNOME/byzanz) on Linux.
```

2022-07-22 10:28 UTC, KendallDoesCoding requested changes

2022-07-22 10:28 UTC, KendallDoesCoding commented on .github/CONTRIBUTING_GUIDE.md
> +* **Include screenshots or animated GIFs** which show you following the described steps and clearly demonstrate the problem. If you use the keyboard while following the steps, use [this tool](https:/
```suggestion
* **Include screenshots or animated GIFs** which show you following the described steps and clearly demonstrate the problem.
```

delete not required text

2022-08-11 14:00 UTC, krshkodes approved these changes
Thank you! Looks great!

2022-08-11 14:00 UTC, merged